export const BUDGET_HIGH_PROTEIN_MEALS = [
  {
    id: 1,
    name: 'Eggs',
    calories: 155,
    protein: 13,
    carbs: 1,
    fats: 11,
    icon: '🥚',
    description: 'Excellent source of high-quality protein',
    ingredients: ['Eggs'],
    servingSize: '2 large eggs',
    prepTime: '5 mins',
  },
  {
    id: 2,
    name: 'Chicken',
    calories: 165,
    protein: 31,
    carbs: 0,
    fats: 3.6,
    icon: '🍗',
    description: 'Lean protein powerhouse',
    ingredients: ['Chicken breast'],
    servingSize: '100g',
    prepTime: '20 mins',
  },
  {
    id: 3,
    name: 'Milk',
    calories: 61,
    protein: 3.2,
    carbs: 4.8,
    fats: 3.3,
    icon: '🥛',
    description: 'Complete protein with calcium',
    ingredients: ['Whole milk'],
    servingSize: '200ml (1 glass)',
    prepTime: '0 mins',
  },
  {
    id: 4,
    name: 'Yogurt/Dahi',
    calories: 59,
    protein: 10,
    carbs: 3,
    fats: 0.4,
    icon: '🥄',
    description: 'Greek yogurt or plain dahi',
    ingredients: ['Plain yogurt'],
    servingSize: '100g',
    prepTime: '0 mins',
  },
  {
    id: 5,
    name: 'Lentils',
    calories: 116,
    protein: 9,
    carbs: 20,
    fats: 0.4,
    icon: '🫘',
    description: 'Protein-rich legume staple',
    ingredients: ['Red or brown lentils'],
    servingSize: '100g cooked',
    prepTime: '25 mins',
  },
  {
    id: 6,
    name: 'Chickpeas',
    calories: 134,
    protein: 7.2,
    carbs: 19,
    fats: 2.5,
    icon: '🫘',
    description: 'Versatile legume with fiber',
    ingredients: ['Chickpeas'],
    servingSize: '100g cooked',
    prepTime: '15 mins',
  },
  {
    id: 7,
    name: 'Kidney Beans',
    calories: 127,
    protein: 8.7,
    carbs: 23,
    fats: 0.3,
    icon: '🫘',
    description: 'High fiber and protein legume',
    ingredients: ['Kidney beans'],
    servingSize: '100g cooked',
    prepTime: '20 mins',
  },
  {
    id: 8,
    name: 'Rice',
    calories: 130,
    protein: 2.7,
    carbs: 28,
    fats: 0.3,
    icon: '🍚',
    description: 'Complete carbohydrate source',
    ingredients: ['White or brown rice'],
    servingSize: '100g cooked',
    prepTime: '20 mins',
  },
  {
    id: 9,
    name: 'Whole Wheat Atta',
    calories: 132,
    protein: 4.3,
    carbs: 27,
    fats: 0.7,
    icon: '🌾',
    description: 'Traditional wheat flour staple',
    ingredients: ['Whole wheat flour'],
    servingSize: '50g (1 roti)',
    prepTime: '10 mins',
  },
  {
    id: 10,
    name: 'Peanuts',
    calories: 159,
    protein: 7.3,
    carbs: 5.6,
    fats: 14,
    icon: '🥜',
    description: 'Nutrient-dense healthy fat source',
    ingredients: ['Raw peanuts'],
    servingSize: '30g (handful)',
    prepTime: '0 mins',
  },
  {
    id: 11,
    name: 'Peanut Butter',
    calories: 188,
    protein: 8,
    carbs: 7,
    fats: 16,
    icon: '🍯',
    description: 'Protein and energy in every spoonful',
    ingredients: ['Ground peanuts'],
    servingSize: '2 tbsp (32g)',
    prepTime: '0 mins',
  },
  {
    id: 12,
    name: 'Bananas',
    calories: 89,
    protein: 1.1,
    carbs: 23,
    fats: 0.3,
    icon: '🍌',
    description: 'Great carb and potassium source',
    ingredients: ['Fresh banana'],
    servingSize: '1 medium banana',
    prepTime: '0 mins',
  },
  {
    id: 13,
    name: 'Dates',
    calories: 66,
    protein: 0.8,
    carbs: 18,
    fats: 0.2,
    icon: '🫐',
    description: 'Natural carbs and quick energy',
    ingredients: ['Dried dates'],
    servingSize: '1 date (20g)',
    prepTime: '0 mins',
  },
  {
    id: 14,
    name: 'Roasted Chana',
    calories: 128,
    protein: 8.2,
    carbs: 18,
    fats: 2,
    icon: '🫘',
    description: 'Crunchy protein and fiber snack',
    ingredients: ['Roasted chickpeas'],
    servingSize: '30g',
    prepTime: '0 mins',
  },
]

